const testQueries = [
  // History (38 queries: 20 original + 18 new)
  { query: "Romance of the Three Kingdoms", expected: "History" },
  { query: "World War II", expected: "History" },
  { query: "ancient egypt", expected: "History" },
  { query: "civil war", expected: "History" },
  { query: "french revolution", expected: "History" },
  { query: "Three Kingdoms", expected: "History" },
  { query: "han dynasty", expected: "History" },
  { query: "world war I", expected: "History" },
  { query: "ancient rome", expected: "History" },
  { query: "medieval europe", expected: "History" },
  { query: "industrial revolution", expected: "History" },
  { query: "qing dynasty", expected: "History" },
  { query: "american revolution", expected: "History" },
  { query: "historical events", expected: "History" },
  { query: "egyptian pyramids", expected: "History" },
  { query: "roman empire", expected: "History" },
  { query: "world history", expected: "History" },
  { query: "colonial america", expected: "History" },
  { query: "byzantine empire", expected: "History" },
  { query: "history of china", expected: "History" },
  { query: "mongol empire", expected: "History" },
  { query: "renaissance history", expected: "History" },
  { query: "ancient greece", expected: "History" },
  { query: "world war 2", expected: "History" },
  { query: "history of japan", expected: "History" },
  { query: "ottoman empire", expected: "History" },
  { query: "histor of rome", expected: "History" }, // 拼寫錯誤
  { query: "viking history", expected: "History" },
  { query: "cold war", expected: "History" },
  { query: "ancient china", expected: "History" },
  { query: "history lessons", expected: "History" },
  { query: "european history", expected: "History" },
  { query: "russian revolution", expected: "History" },
  { query: "history timeline", expected: "History" },
  { query: "ancient civilizations", expected: "History" },
  { query: "world wars", expected: "History" },
  { query: "historical figures", expected: "History" },
  { query: "history education", expected: "History" },

  // Chinese Language Education (36 queries: 18 original + 18 new)
  { query: "learn mandarin", expected: "Chinese Language Education" },
  { query: "chinese language", expected: "Chinese Language Education" },
  { query: "pinyin practice", expected: "Chinese Language Education" },
  { query: "hanzi writing", expected: "Chinese Language Education" },
  { query: "cantonese basics", expected: "Chinese Language Education" },
  { query: "chinese literature", expected: "Chinese Language Education" },
  { query: "mandarin speaking", expected: "Chinese Language Education" },
  { query: "chinese grammar", expected: "Chinese Language Education" },
  { query: "learn hanzi", expected: "Chinese Language Education" },
  { query: "pinyin tones", expected: "Chinese Language Education" },
  { query: "chinese culture", expected: "Chinese Language Education" },
  { query: "mandarin vocabulary", expected: "Chinese Language Education" },
  { query: "cantonese pronunciation", expected: "Chinese Language Education" },
  { query: "chinese characters", expected: "Chinese Language Education" },
  { query: "learn pinyin", expected: "Chinese Language Education" },
  { query: "chinese poetry", expected: "Chinese Language Education" },
  { query: "mandarin course", expected: "Chinese Language Education" },
  { query: "chinese language skills", expected: "Chinese Language Education" },
  { query: "mandarin lessons", expected: "Chinese Language Education" },
  { query: "chinese writing skills", expected: "Chinese Language Education" },
  { query: "learn cantonese", expected: "Chinese Language Education" },
  { query: "hanzi practice", expected: "Chinese Language Education" },
  { query: "mandarin pronuciation", expected: "Chinese Language Education" }, // 拼寫錯誤
  { query: "chinese idioms", expected: "Chinese Language Education" },
  { query: "pinyin exercises", expected: "Chinese Language Education" },
  { query: "chinese language course", expected: "Chinese Language Education" },
  { query: "cantonese lessons", expected: "Chinese Language Education" },
  { query: "chinese calligraphy", expected: "Chinese Language Education" },
  { query: "mandarin fluency", expected: "Chinese Language Education" },
  { query: "chinese reading", expected: "Chinese Language Education" },
  { query: "learn chinese online", expected: "Chinese Language Education" },
  { query: "chinese language basics", expected: "Chinese Language Education" },
  { query: "hanzi recognition", expected: "Chinese Language Education" },
  { query: "chinese conversation", expected: "Chinese Language Education" },
  { query: "mandarin grammar", expected: "Chinese Language Education" },
  { query: "chinese language learning", expected: "Chinese Language Education" },

  // English Language Education (36 queries: 18 original + 18 new)
  { query: "english grammar", expected: "English Language Education" },
  { query: "learn english", expected: "English Language Education" },
  { query: "esl teaching", expected: "English Language Education" },
  { query: "english vocabulary", expected: "English Language Education" },
  { query: "writing skills", expected: "English Language Education" },
  { query: "english literature", expected: "English Language Education" },
  { query: "grammar rules", expected: "English Language Education" },
  { query: "english pronunciation", expected: "English Language Education" },
  { query: "essay writing", expected: "English Language Education" },
  { query: "english speaking", expected: "English Language Education" },
  { query: "vocabulary building", expected: "English Language Education" },
  { query: "english comprehension", expected: "English Language Education" },
  { query: "esl resources", expected: "English Language Education" },
  { query: "english writing", expected: "English Language Education" },
  { query: "grammar exercises", expected: "English Language Education" },
  { query: "english language course", expected: "English Language Education" },
  { query: "reading comprehension", expected: "English Language Education" },
  { query: "english idioms", expected: "English Language Education" },
  { query: "english fluency", expected: "English Language Education" },
  { query: "learn esl", expected: "English Language Education" },
  { query: "english conversation", expected: "English Language Education" },
  { query: "grammer practice", expected: "English Language Education" }, // 拼寫錯誤
  { query: "english reading skills", expected: "English Language Education" },
  { query: "esl lessons", expected: "English Language Education" },
  { query: "english writing skills", expected: "English Language Education" },
  { query: "vocabulary exercises", expected: "English Language Education" },
  { query: "english language basics", expected: "English Language Education" },
  { query: "english speaking practice", expected: "English Language Education" },
  { query: "english literature analysis", expected: "English Language Education" },
  { query: "learn english online", expected: "English Language Education" },
  { query: "english grammar course", expected: "English Language Education" },
  { query: "esl speaking", expected: "English Language Education" },
  { query: "english essay tips", expected: "English Language Education" },
  { query: "reading skills english", expected: "English Language Education" },
  { query: "english language learning", expected: "English Language Education" },
  { query: "english vocab practice", expected: "English Language Education" },

  // Mathematics Education (36 queries: 18 original + 18 new)
  { query: "algebra basics", expected: "Mathematics Education" },
  { query: "math calculus", expected: "Mathematics Education" },
  { query: "geometry problems", expected: "Mathematics Education" },
  { query: "trigonometry formulas", expected: "Mathematics Education" },
  { query: "statistics course", expected: "Mathematics Education" },
  { query: "calculus derivatives", expected: "Mathematics Education" },
  { query: "math equations", expected: "Mathematics Education" },
  { query: "algebraic expressions", expected: "Mathematics Education" },
  { query: "geometry theorems", expected: "Mathematics Education" },
  { query: "probability theory", expected: "Mathematics Education" },
  { query: "maths tutorial", expected: "Mathematics Education" },
  { query: "trigonometric functions", expected: "Mathematics Education" },
  { query: "linear algebra", expected: "Mathematics Education" },
  { query: "calculus integrals", expected: "Mathematics Education" },
  { query: "math problem solving", expected: "Mathematics Education" },
  { query: "statistics data analysis", expected: "Mathematics Education" },
  { query: "geometry shapes", expected: "Mathematics Education" },
  { query: "math education", expected: "Mathematics Education" },
  { query: "maths basics", expected: "Mathematics Education" },
  { query: "algebra lessons", expected: "Mathematics Education" },
  { query: "calculus course", expected: "Mathematics Education" },
  { query: "geomtry problems", expected: "Mathematics Education" }, // 拼寫錯誤
  { query: "statistics basics", expected: "Mathematics Education" },
  { query: "math for beginners", expected: "Mathematics Education" },
  { query: "trigonometry lessons", expected: "Mathematics Education" },
  { query: "probability problems", expected: "Mathematics Education" },
  { query: "math tutorials online", expected: "Mathematics Education" },
  { query: "algebra practice", expected: "Mathematics Education" },
  { query: "calculus problems", expected: "Mathematics Education" },
  { query: "geometry education", expected: "Mathematics Education" },
  { query: "math skills", expected: "Mathematics Education" },
  { query: "statistics lessons", expected: "Mathematics Education" },
  { query: "linear algebra course", expected: "Mathematics Education" },
  { query: "math problem sets", expected: "Mathematics Education" },
  { query: "trigonometry basics", expected: "Mathematics Education" },
  { query: "maths learning", expected: "Mathematics Education" },

  // Science Education (36 queries: 18 original + 18 new)
  { query: "photosynthesis process", expected: "Science Education" },
  { query: "quantum mechanics", expected: "Science Education" },
  { query: "chemical reactions", expected: "Science Education" },
  { query: "biology cells", expected: "Science Education" },
  { query: "physics mechanics", expected: "Science Education" },
  { query: "astronomy stars", expected: "Science Education" },
  { query: "earth science", expected: "Science Education" },
  { query: "genetics basics", expected: "Science Education" },
  { query: "thermodynamics laws", expected: "Science Education" },
  { query: "science experiments", expected: "Science Education" },
  { query: "chemistry periodic table", expected: "Science Education" },
  { query: "biology evolution", expected: "Science Education" },
  { query: "physics electricity", expected: "Science Education" },
  { query: "astronomy planets", expected: "Science Education" },
  { query: "environmental science", expected: "Science Education" },
  { query: "science education", expected: "Science Education" },
  { query: "chemical bonding", expected: "Science Education" },
  { query: "physics optics", expected: "Science Education" },
  { query: "biology basics", expected: "Science Education" },
  { query: "physics experiments", expected: "Science Education" },
  { query: "chemestry reactions", expected: "Science Education" }, // 拼寫錯誤
  { query: "astronomy basics", expected: "Science Education" },
  { query: "genetics course", expected: "Science Education" },
  { query: "earth science lessons", expected: "Science Education" },
  { query: "science for beginners", expected: "Science Education" },
  { query: "physics course", expected: "Science Education" },
  { query: "biology lessons", expected: "Science Education" },
  { query: "chemistry basics", expected: "Science Education" },
  { query: "science learning", expected: "Science Education" },
  { query: "environmental studies", expected: "Science Education" },
  { query: "astronomy education", expected: "Science Education" },
  { query: "physics mechanics course", expected: "Science Education" },
  { query: "biology experiments", expected: "Science Education" },
  { query: "chemistry lessons", expected: "Science Education" },
  { query: "science projects", expected: "Science Education" },
  { query: "genetics research", expected: "Science Education" },

  // Social and Humanistic Education (36 queries: 18 original + 18 new)
  { query: "sociology theories", expected: "Social and Humanistic Education" },
  { query: "psychology basics", expected: "Social and Humanistic Education" },
  { query: "philosophy ethics", expected: "Social and Humanistic Education" },
  { query: "anthropology cultures", expected: "Social and Humanistic Education" },
  { query: "social studies", expected: "Social and Humanistic Education" },
  { query: "humanities overview", expected: "Social and Humanistic Education" },
  { query: "psychology behavior", expected: "Social and Humanistic Education" },
  { query: "sociology research", expected: "Social and Humanistic Education" },
  { query: "philosophy logic", expected: "Social and Humanistic Education" },
  { query: "cultural anthropology", expected: "Social and Humanistic Education" },
  { query: "social science", expected: "Social and Humanistic Education" },
  { query: "humanities studies", expected: "Social and Humanistic Education" },
  { query: "psychology cognition", expected: "Social and Humanistic Education" },
  { query: "sociology inequality", expected: "Social and Humanistic Education" },
  { query: "philosophy metaphysics", expected: "Social and Humanistic Education" },
  { query: "anthropology fieldwork", expected: "Social and Humanistic Education" },
  { query: "social theory", expected: "Social and Humanistic Education" },
  { query: "humanistic education", expected: "Social and Humanistic Education" },
  { query: "psychology course", expected: "Social and Humanistic Education" },
  { query: "sociology basics", expected: "Social and Humanistic Education" },
  { query: "philosophy basics", expected: "Social and Humanistic Education" },
  { query: "anthropolgy cultures", expected: "Social and Humanistic Education" }, // 拼寫錯誤
  { query: "social science research", expected: "Social and Humanistic Education" },
  { query: "humanities education", expected: "Social and Humanistic Education" },
  { query: "psychology studies", expected: "Social and Humanistic Education" },
  { query: "sociology lessons", expected: "Social and Humanistic Education" },
  { query: "philosophy course", expected: "Social and Humanistic Education" },
  { query: "cultural studies", expected: "Social and Humanistic Education" },
  { query: "social studies course", expected: "Social and Humanistic Education" },
  { query: "psychology behavior studies", expected: "Social and Humanistic Education" },
  { query: "sociology education", expected: "Social and Humanistic Education" },
  { query: "philosophy ethics course", expected: "Social and Humanistic Education" },
  { query: "anthropology basics", expected: "Social and Humanistic Education" },
  { query: "humanities research", expected: "Social and Humanistic Education" },
  { query: "social science basics", expected: "Social and Humanistic Education" },
  { query: "psychology learning", expected: "Social and Humanistic Education" },

  // Physical Education (36 queries: 18 original + 18 new)
  { query: "physical fitness", expected: "Physical Education" },
  { query: "sports training", expected: "Physical Education" },
  { query: "exercise routines", expected: "Physical Education" },
  { query: "athletics coaching", expected: "Physical Education" },
  { query: "health education", expected: "Physical Education" },
  { query: "physical education", expected: "Physical Education" },
  { query: "fitness programs", expected: "Physical Education" },
  { query: "sports science", expected: "Physical Education" },
  { query: "exercise physiology", expected: "Physical Education" },
  { query: "athletic performance", expected: "Physical Education" },
  { query: "health and fitness", expected: "Physical Education" },
  { query: "sports skills", expected: "Physical Education" },
  { query: "physical training", expected: "Physical Education" },
  { query: "fitness coaching", expected: "Physical Education" },
  { query: "sports management", expected: "Physical Education" },
  { query: "exercise science", expected: "Physical Education" },
  { query: "athletics programs", expected: "Physical Education" },
  { query: "physical activity", expected: "Physical Education" },
  { query: "fitness training", expected: "Physical Education" },
  { query: "sports coaching", expected: "Physical Education" },
  { query: "excercise routines", expected: "Physical Education" }, // 拼寫錯誤
  { query: "athletics basics", expected: "Physical Education" },
  { query: "health and wellness", expected: "Physical Education" },
  { query: "sports education", expected: "Physical Education" },
  { query: "physical education course", expected: "Physical Education" },
  { query: "fitness lessons", expected: "Physical Education" },
  { query: "sports performance", expected: "Physical Education" },
  { query: "exercise programs", expected: "Physical Education" },
  { query: "athletic training course", expected: "Physical Education" },
  { query: "sports science course", expected: "Physical Education" },
  { query: "physical fitness course", expected: "Physical Education" },
  { query: "health education course", expected: "Physical Education" },
  { query: "sports skills training", expected: "Physical Education" },
  { query: "fitness education", expected: "Physical Education" },
  { query: "physical education basics", expected: "Physical Education" },
  { query: "sports and fitness", expected: "Physical Education" },

  // Arts and Humanities (36 queries: 18 original + 18 new)
  { query: "shakespeare hamlet", expected: "Arts and Humanities" },
  { query: "music theory", expected: "Arts and Humanities" },
  { query: "literature analysis", expected: "Arts and Humanities" },
  { query: "visual arts", expected: "Arts and Humanities" },
  { query: "theater performance", expected: "Arts and Humanities" },
  { query: "humanities studies", expected: "Arts and Humanities" },
  { query: "classical music", expected: "Arts and Humanities" },
  { query: "modern art", expected: "Arts and Humanities" },
  { query: "literary criticism", expected: "Arts and Humanities" },
  { query: "art appreciation", expected: "Arts and Humanities" },
  { query: "theater history", expected: "Arts and Humanities" },
  { query: "music composition", expected: "Arts and Humanities" },
  { query: "literature classics", expected: "Arts and Humanities" },
  { query: "visual art techniques", expected: "Arts and Humanities" },
  { query: "arts education", expected: "Arts and Humanities" },
  { query: "humanities research", expected: "Arts and Humanities" },
  { query: "shakespeare sonnets", expected: "Arts and Humanities" },
  { query: "art history", expected: "Arts and Humanities" },
  { query: "music education", expected: "Arts and Humanities" },
  { query: "literature studies", expected: "Arts and Humanities" },
  { query: "theatre performance", expected: "Arts and Humanities" }, // 拼寫錯誤
  { query: "visual arts course", expected: "Arts and Humanities" },
  { query: "classical music course", expected: "Arts and Humanities" },
  { query: "art appreciation course", expected: "Arts and Humanities" },
  { query: "literature course", expected: "Arts and Humanities" },
  { query: "music composition course", expected: "Arts and Humanities" },
  { query: "shakespeare studies", expected: "Arts and Humanities" },
  { query: "arts and humanities basics", expected: "Arts and Humanities" },
  { query: "theater education", expected: "Arts and Humanities" },
  { query: "visual arts basics", expected: "Arts and Humanities" },
  { query: "literature analysis course", expected: "Arts and Humanities" },
  { query: "music theory course", expected: "Arts and Humanities" },
  { query: "arts learning", expected: "Arts and Humanities" },
  { query: "humanities course", expected: "Arts and Humanities" },
  { query: "art history course", expected: "Arts and Humanities" },
  { query: "literature classics course", expected: "Arts and Humanities" },

  // Business and Communication (36 queries: 18 original + 18 new)
  { query: "marketing strategies", expected: "Business and Communication" },
  { query: "business finance", expected: "Business and Communication" },
  { query: "management skills", expected: "Business and Communication" },
  { query: "economics principles", expected: "Business and Communication" },
  { query: "communication skills", expected: "Business and Communication" },
  { query: "business strategies", expected: "Business and Communication" },
  { query: "marketing campaigns", expected: "Business and Communication" },
  { query: "financial analysis", expected: "Business and Communication" },
  { query: "management theories", expected: "Business and Communication" },
  { query: "business communication", expected: "Business and Communication" },
  { query: "economics markets", expected: "Business and Communication" },
  { query: "public relations", expected: "Business and Communication" },
  { query: "business planning", expected: "Business and Communication" },
  { query: "marketing research", expected: "Business and Communication" },
  { query: "financial management", expected: "Business and Communication" },
  { query: "corporate communication", expected: "Business and Communication" },
  { query: "economics policies", expected: "Business and Communication" },
  { query: "business leadership", expected: "Business and Communication" },
  { query: "business basics", expected: "Business and Communication" },
  { query: "marketing basics", expected: "Business and Communication" },
  { query: "managment skills", expected: "Business and Communication" }, // 拼寫錯誤
  { query: "economics course", expected: "Business and Communication" },
  { query: "communication course", expected: "Business and Communication" },
  { query: "business education", expected: "Business and Communication" },
  { query: "marketing course", expected: "Business and Communication" },
  { query: "financial planning", expected: "Business and Communication" },
  { query: "business leadership course", expected: "Business and Communication" },
  { query: "public relations course", expected: "Business and Communication" },
  { query: "economics basics", expected: "Business and Communication" },
  { query: "business strategies course", expected: "Business and Communication" },
  { query: "communication skills course", expected: "Business and Communication" },
  { query: "marketing strategies course", expected: "Business and Communication" },
  { query: "business finance course", expected: "Business and Communication" },
  { query: "management basics", expected: "Business and Communication" },
  { query: "business learning", expected: "Business and Communication" },
  { query: "economics education", expected: "Business and Communication" },

  // Career and Technical Education (36 queries: 18 original + 18 new)
  { query: "coding bootcamp", expected: "Career and Technical Education" },
  { query: "vocational training", expected: "Career and Technical Education" },
  { query: "technical education", expected: "Career and Technical Education" },
  { query: "engineering basics", expected: "Career and Technical Education" },
  { query: "computer science", expected: "Career and Technical Education" },
  { query: "trade skills", expected: "Career and Technical Education" },
  { query: "career skills", expected: "Career and Technical Education" },
  { query: "programming basics", expected: "Career and Technical Education" },
  { query: "engineering design", expected: "Career and Technical Education" },
  { query: "technical skills", expected: "Career and Technical Education" },
  { query: "vocational courses", expected: "Career and Technical Education" },
  { query: "computer programming", expected: "Career and Technical Education" },
  { query: "engineering projects", expected: "Career and Technical Education" },
  { query: "trade certification", expected: "Career and Technical Education" },
  { query: "career training", expected: "Career and Technical Education" },
  { query: "technical training", expected: "Career and Technical Education" },
  { query: "coding skills", expected: "Career and Technical Education" },
  { query: "engineering technology", expected: "Career and Technical Education" },
  { query: "learn coding", expected: "Career and Technical Education" },
  { query: "software engineering", expected: "Career and Technical Education" },
  { query: "programing basics", expected: "Career and Technical Education" }, // 拼寫錯誤
  { query: "technical courses", expected: "Career and Technical Education" },
  { query: "engineering course", expected: "Career and Technical Education" },
  { query: "computer science course", expected: "Career and Technical Education" },
  { query: "vocational education", expected: "Career and Technical Education" },
  { query: "coding lessons", expected: "Career and Technical Education" },
  { query: "trade skills course", expected: "Career and Technical Education" },
  { query: "career development", expected: "Career and Technical Education" },
  { query: "technical skills course", expected: "Career and Technical Education" },
  { query: "engineering basics course", expected: "Career and Technical Education" },
  { query: "programming course", expected: "Career and Technical Education" },
  { query: "computer science basics", expected: "Career and Technical Education" },
  { query: "vocational skills", expected: "Career and Technical Education" },
  { query: "coding education", expected: "Career and Technical Education" },
  { query: "technical education course", expected: "Career and Technical Education" },
  { query: "career skills course", expected: "Career and Technical Education" },

  // General Studies (36 queries: 18 original + 18 new)
  { query: "liberal arts", expected: "General Studies" },
  { query: "general studies", expected: "General Studies" },
  { query: "study skills", expected: "General Studies" },
  { query: "academic writing", expected: "General Studies" },
  { query: "interdisciplinary studies", expected: "General Studies" },
  { query: "critical thinking", expected: "General Studies" },
  { query: "research skills", expected: "General Studies" },
  { query: "general education", expected: "General Studies" },
  { query: "study techniques", expected: "General Studies" },
  { query: "academic skills", expected: "General Studies" },
  { query: "interdisciplinary research", expected: "General Studies" },
  { query: "writing for college", expected: "General Studies" },
  { query: "liberal arts education", expected: "General Studies" },
  { query: "study strategies", expected: "General Studies" },
  { query: "general knowledge", expected: "General Studies" },
  { query: "academic research", expected: "General Studies" },
  { query: "critical analysis", expected: "General Studies" },
  { query: "general studies course", expected: "General Studies" },
  { query: "study habits", expected: "General Studies" },
  { query: "college writing", expected: "General Studies" },
  { query: "academc skills", expected: "General Studies" }, // 拼寫錯誤
  { query: "general education course", expected: "General Studies" },
  { query: "liberal arts course", expected: "General Studies" },
  { query: "study skills course", expected: "General Studies" },
  { query: "critical thinking course", expected: "General Studies" },
  { query: "research skills course", expected: "General Studies" },
  { query: "interdisciplinary education", expected: "General Studies" },
  { query: "academic writing course", expected: "General Studies" },
  { query: "general studies basics", expected: "General Studies" },
  { query: "study techniques course", expected: "General Studies" },
  { query: "liberal arts basics", expected: "General Studies" },
  { query: "general knowledge course", expected: "General Studies" },
  { query: "critical thinking skills", expected: "General Studies" },
  { query: "academic research course", expected: "General Studies" },
  { query: "study strategies course", expected: "General Studies" },
  { query: "general education basics", expected: "General Studies" },

  // No-match queries (20 queries: 10 original + 10 new)
  { query: "random topic", expected: null },
  { query: "unrelated subject", expected: null },
  { query: "miscellaneous", expected: null },
  { query: "generic query", expected: null },
  { query: "unknown topic", expected: null },
  { query: "vague term", expected: null },
  { query: "non academic", expected: null },
  { query: "irrelevant search", expected: null },
  { query: "off topic", expected: null },
  { query: "no subject", expected: null },
  { query: "unspecified topic", expected: null },
  { query: "general question", expected: null },
  { query: "random search", expected: null },
  { query: "non educational", expected: null },
  { query: "misc topic", expected: null },
  { query: "vague query", expected: null },
  { query: "unrelated query", expected: null },
  { query: "generic topic", expected: null },
  { query: "off subject", expected: null },
  { query: "no category", expected: null },
];

module.exports = testQueries;