const testQueries = [
  // History (38 queries)
  { query: "Terracotta Army origins", expected: "History" },
  { query: "Gulf War events", expected: "History" },
  { query: "sumerian culture", expected: "History" },
  { query: "Battle of New Orleans", expected: "History" },
  { query: "october uprising", expected: "History" },
  { query: "Song era governance", expected: "History" },
  { query: "witch hunts spain", expected: "History" },
  { query: "Korean conflict 1950s", expected: "History" },
  { query: "Trojan War tales", expected: "History" },
  { query: "samurai governance", expected: "History" },
  { query: "philosopher kings era", expected: "History" },
  { query: "Yuan era trade", expected: "History" },
  { query: "taxation revolt 1773", expected: "History" },
  { query: "battle strategies past", expected: "History" },
  { query: "Aztec societal collapse", expected: "History" },
  { query: "Roman decline causes", expected: "History" },
  { query: "planetary historical trends", expected: "History" },
  { query: "Massachusetts trials 1692", expected: "History" },
  { query: "Germanic empire 800s", expected: "History" },
  { query: "Asian imperial cycles", expected: "History" },
  { query: "medieval holy wars", expected: "History" },
  { query: "ornate architecture 1600s", expected: "History" },
  { query: "Greek voting systems", expected: "History" },
  { query: "Great War 1914", expected: "History" },
  { query: "Japanese warring states", expected: "History" },
  { query: "Achaemenid conquests", expected: "History" },
  { query: "histary of pharaohs", expected: "History" }, // Misspelling
  { query: "English invasion 1066", expected: "History" },
  { query: "moon landing rivalry", expected: "History" },
  { query: "Zhou era philosophy", expected: "History" },
  { query: "past events syllabus", expected: "History" },
  { query: "Mali empire trade", expected: "History" },
  { query: "Castro’s uprising", expected: "History" },
  { query: "epochs of humanity", expected: "History" },
  { query: " Andean civilizations", expected: "History" },
  { query: "global warfare eras", expected: "History" },
  { query: "rulers of antiquity", expected: "History" },
  { query: "chronicles of nations", expected: "History" },

  // Chinese Language Education (36 queries)
  { query: "Beijing dialect sounds", expected: "Chinese Language Education" },
  { query: "Sino linguistic patterns", expected: "Chinese Language Education" },
  { query: "ideograph stroke sequence", expected: "Chinese Language Education" },
  { query: "Hong Kong dialect terms", expected: "Chinese Language Education" },
  { query: "Tang poetry narratives", expected: "Chinese Language Education" },
  { query: "Northern dialect ear training", expected: "Chinese Language Education" },
  { query: "Sino sentence frameworks", expected: "Chinese Language Education" },
  { query: "mastering ideographs", expected: "Chinese Language Education" },
  { query: "tonal sound practice", expected: "Chinese Language Education" },
  { query: "Eastern cultural narratives", expected: "Chinese Language Education" },
  { query: "Northern dialect phrases", expected: "Chinese Language Education" },
  { query: "Southern dialect syntax", expected: "Chinese Language Education" },
  { query: "Sino writing systems", expected: "Chinese Language Education" },
  { query: "tonal rhythm exercises", expected: "Chinese Language Education" },
  { query: "ancient Sino texts", expected: "Chinese Language Education" },
  { query: "Beijing speech coaching", expected: "Chinese Language Education" },
  { query: "Sino linguistic mastery", expected: "Chinese Language Education" },
  { query: "Northern dialect exchanges", expected: "Chinese Language Education" },
  { query: "Sino essay crafting", expected: "Chinese Language Education" },
  { query: "learn Southern dialect", expected: "Chinese Language Education" },
  { query: "ideograph retention", expected: "Chinese Language Education" },
  { query: "Beijing pronounciation", expected: "Chinese Language Education" }, // Misspelling
  { query: "Sino sayings", expected: "Chinese Language Education" },
  { query: "tonal speech lessons", expected: "Chinese Language Education" },
  { query: "Sino linguistic curriculum", expected: "Chinese Language Education" },
  { query: "Hong Kong dialect oration", expected: "Chinese Language Education" },
  { query: "Sino calligraphy art", expected: "Chinese Language Education" },
  { query: "Northern speech fluency", expected: "Chinese Language Education" },
  { query: "Sino textual critique", expected: "Chinese Language Education" },
  { query: "virtual Sino studies", expected: "Chinese Language Education" },
  { query: "Sino linguistic basics", expected: "Chinese Language Education" },
  { query: "ideograph spotting", expected: "Chinese Language Education" },
  { query: "Sino conversational drills", expected: "Chinese Language Education" },
  { query: "Beijing dialect syntax", expected: "Chinese Language Education" },
  { query: "Sino speech curriculum", expected: "Chinese Language Education" },
  { query: "Sino oratory skills", expected: "Chinese Language Education" },

  // English Language Education (36 queries)
  { query: "Anglo linguistic structure", expected: "English Language Education" },
  { query: "mastering Anglo speech", expected: "English Language Education" },
  { query: "non-native speaker syllabus", expected: "English Language Education" },
  { query: "Anglo lexical expansion", expected: "English Language Education" },
  { query: "narrative composition", expected: "English Language Education" },
  { query: "Victorian novels", expected: "English Language Education" },
  { query: "sentence construction norms", expected: "English Language Education" },
  { query: "Anglo sound articulation", expected: "English Language Education" },
  { query: "persuasive writing tasks", expected: "English Language Education" },
  { query: "Anglo verbal skills", expected: "English Language Education" },
  { query: "word creation patterns", expected: "English Language Education" },
  { query: "Anglo text reading", expected: "English Language Education" },
  { query: "non-native teaching aids", expected: "English Language Education" },
  { query: "Anglo prose crafting", expected: "English Language Education" },
  { query: "sentence drills", expected: "English Language Education" },
  { query: "Anglo linguistic program", expected: "English Language Education" },
  { query: "text interpretation skills", expected: "English Language Education" },
  { query: "Anglo colloquial phrases", expected: "English Language Education" },
  { query: "Anglo speech mastery", expected: "English Language Education" },
  { query: "non-native mentoring", expected: "English Language Education" },
  { query: "Anglo conversational skills", expected: "English Language Education" },
  { query: "gramar practice", expected: "English Language Education" }, // Misspelling
  { query: "Anglo reading proficiency", expected: "English Language Education" },
  { query: "non-native guidance", expected: "English Language Education" },
  { query: "Anglo essay techniques", expected: "English Language Education" },
  { query: "lexical drills", expected: "English Language Education" },
  { query: "Anglo linguistic foundations", expected: "English Language Education" },
  { query: "Anglo oratory practice", expected: "English Language Education" },
  { query: "Anglo fiction critique", expected: "English Language Education" },
  { query: "virtual Anglo learning", expected: "English Language Education" },
  { query: "Anglo sentence course", expected: "English Language Education" },
  { query: "non-native dialogue", expected: "English Language Education" },
  { query: "Anglo composition tips", expected: "English Language Education" },
  { query: "Anglo text analysis", expected: "English Language Education" },
  { query: "Anglo linguistic studies", expected: "English Language Education" },
  { query: "Anglo word drills", expected: "English Language Education" },

  // Mathematics Education (36 queries)
  { query: "equation solving basics", expected: "Mathematics Education" },
  { query: "differential concepts", expected: "Mathematics Education" },
  { query: "shape theorems", expected: "Mathematics Education" },
  { query: "angular ratios", expected: "Mathematics Education" },
  { query: "numerical analysis", expected: "Mathematics Education" },
  { query: "slope calculations", expected: "Mathematics Education" },
  { query: "quantitative rules", expected: "Mathematics Education" },
  { query: "polynomial solutions", expected: "Mathematics Education" },
  { query: "spatial axioms", expected: "Mathematics Education" },
  { query: "chance calculations", expected: "Mathematics Education" },
  { query: "numerical tutoring", expected: "Mathematics Education" },
  { query: "angular equations", expected: "Mathematics Education" },
  { query: "vector mathematics", expected: "Mathematics Education" },
  { query: "area under curves", expected: "Mathematics Education" },
  { query: "quantitative puzzles", expected: "Mathematics Education" },
  { query: "data interpretation methods", expected: "Mathematics Education" },
  { query: "polygonal forms", expected: "Mathematics Education" },
  { query: "numerical studies", expected: "Mathematics Education" },
  { query: "quantitative foundations", expected: "Mathematics Education" },
  { query: "equation coaching", expected: "Mathematics Education" },
  { query: "differential tutoring", expected: "Mathematics Education" },
  { query: "geomtery axioms", expected: "Mathematics Education" }, // Misspelling
  { query: "basic data analysis", expected: "Mathematics Education" },
  { query: "numerical essentials", expected: "Mathematics Education" },
  { query: "angular coaching", expected: "Mathematics Education" },
  { query: "chance exercises", expected: "Mathematics Education" },
  { query: "virtual numerical lessons", expected: "Mathematics Education" },
  { query: "polynomial drills", expected: "Mathematics Education" },
  { query: "differential exercises", expected: "Mathematics Education" },
  { query: "spatial studies", expected: "Mathematics Education" },
  { query: "quantitative proficiency", expected: "Mathematics Education" },
  { query: "data coaching", expected: "Mathematics Education" },
  { query: "vector mathematics course", expected: "Mathematics Education" },
  { query: "numerical tasks", expected: "Mathematics Education" },
  { query: "angular essentials", expected: "Mathematics Education" },
  { query: "quantitative syllabus", expected: "Mathematics Education" },

  // Science Education (36 queries)
  { query: "mitosis phases", expected: "Science Education" },
  { query: "Einstein’s equations", expected: "Science Education" },
  { query: "carbon compounds", expected: "Science Education" },
  { query: "ecosystem dynamics", expected: "Science Education" },
  { query: "motion laws", expected: "Science Education" },
  { query: "stellar evolution", expected: "Science Education" },
  { query: "rock formations", expected: "Science Education" },
  { query: "genetic code", expected: "Science Education" },
  { query: "energy transfer", expected: "Science Education" },
  { query: "laboratory tasks", expected: "Science Education" },
  { query: "atomic models", expected: "Science Education" },
  { query: "evolutionary mechanisms", expected: "Science Education" },
  { query: "magnetic fields", expected: "Science Education" },
  { query: "planetary orbits", expected: "Science Education" },
  { query: "weather patterns", expected: "Science Education" },
  { query: "natural sciences syllabus", expected: "Science Education" },
  { query: "covalent links", expected: "Science Education" },
  { query: "light refraction", expected: "Science Education" },
  { query: "cellular basics", expected: "Science Education" },
  { query: "motion experiments", expected: "Science Education" },
  { query: "chemestry essentials", expected: "Science Education" }, // Misspelling
  { query: "cosmic studies", expected: "Science Education" },
  { query: "heredity research", expected: "Science Education" },
  { query: "earth strata lessons", expected: "Science Education" },
  { query: "natural sciences basics", expected: "Science Education" },
  { query: "motion tutoring", expected: "Science Education" },
  { query: "cellular syllabus", expected: "Science Education" },
  { query: "molecular essentials", expected: "Science Education" },
  { query: "natural sciences studies", expected: "Science Education" },
  { query: "ecosystem research", expected: "Science Education" },
  { query: "stellar syllabus", expected: "Science Education" },
  { query: "force dynamics", expected: "Science Education" },
  { query: "cellular experiments", expected: "Science Education" },
  { query: "molecular tutoring", expected: "Science Education" },
  { query: "scientific inquiries", expected: "Science Education" },
  { query: "heredity experiments", expected: "Science Education" },

  // Social and Humanistic Education (36 queries)
  { query: "societal frameworks", expected: "Social and Humanistic Education" },
  { query: "mental processes", expected: "Social and Humanistic Education" },
  { query: "ethical reasoning", expected: "Social and Humanistic Education" },
  { query: "cultural fieldwork", expected: "Social and Humanistic Education" },
  { query: "citizenship studies", expected: "Social and Humanistic Education" },
  { query: "cultural essentials", expected: "Social and Humanistic Education" },
  { query: "human behavior studies", expected: "Social and Humanistic Education" },
  { query: "societal inquiries", expected: "Social and Humanistic Education" },
  { query: "logical inquiry", expected: "Social and Humanistic Education" },
  { query: "ethnographic analysis", expected: "Social and Humanistic Education" },
  { query: "human sciences", expected: "Social and Humanistic Education" },
  { query: "cultural syllabus", expected: "Social and Humanistic Education" },
  { query: "cognitive theories", expected: "Social and Humanistic Education" },
  { query: "social disparities", expected: "Social and Humanistic Education" },
  { query: "existential thought", expected: "Social and Humanistic Education" },
  { query: "cultural investigations", expected: "Social and Humanistic Education" },
  { query: "societal models", expected: "Social and Humanistic Education" },
  { query: "humanistic inquiries", expected: "Social and Humanistic Education" },
  { query: "mental essentials", expected: "Social and Humanistic Education" },
  { query: "societal essentials", expected: "Social and Humanistic Education" },
  { query: "ethical studies", expected: "Social and Humanistic Education" },
  { query: "anthrpology inquiries", expected: "Social and Humanistic Education" }, // Misspelling
  { query: "human sciences syllabus", expected: "Social and Humanistic Education" },
  { query: "cultural foundations", expected: "Social and Humanistic Education" },
  { query: "mental research", expected: "Social and Humanistic Education" },
  { query: "societal syllabus", expected: "Social and Humanistic Education" },
  { query: "ethical syllabus", expected: "Social and Humanistic Education" },
  { query: "ethnographic research", expected: "Social and Humanistic Education" },
  { query: "citizenship syllabus", expected: "Social and Humanistic Education" },
  { query: "behavioral inquiries", expected: "Social and Humanistic Education" },
  { query: "societal curriculum", expected: "Social and Humanistic Education" },
  { query: "moral inquiry course", expected: "Social and Humanistic Education" },
  { query: "cultural essentials course", expected: "Social and Humanistic Education" },
  { query: "cultural explorations", expected: "Social and Humanistic Education" },
  { query: "human sciences essentials", expected: "Social and Humanistic Education" },
  { query: "mental studies syllabus", expected: "Social and Humanistic Education" },

  // Physical Education (36 queries)
  { query: "body conditioning", expected: "Physical Education" },
  { query: "team coaching", expected: "Physical Education" },
  { query: "training regimens", expected: "Physical Education" },
  { query: "game conditioning", expected: "Physical Education" },
  { query: "health awareness", expected: "Physical Education" },
  { query: "movement syllabus", expected: "Physical Education" },
  { query: "workout schedules", expected: "Physical Education" },
  { query: "body mechanics", expected: "Physical Education" },
  { query: "muscle physiology", expected: "Physical Education" },
  { query: "competitive skills", expected: "Physical Education" },
  { query: "wellness routines", expected: "Physical Education" },
  { query: "game techniques", expected: "Physical Education" },
  { query: "body training", expected: "Physical Education" },
  { query: "workout guidance", expected: "Physical Education" },
  { query: "team management", expected: "Physical Education" },
  { query: "movement studies", expected: "Physical Education" },
  { query: "competitive programs", expected: "Physical Education" },
  { query: "body wellness", expected: "Physical Education" },
  { query: "training workouts", expected: "Physical Education" },
  { query: "game coaching", expected: "Physical Education" },
  { query: "exercize regimens", expected: "Physical Education" }, // Misspelling
  { query: "competitive essentials", expected: "Physical Education" },
  { query: "health routines", expected: "Physical Education" },
  { query: "game syllabus", expected: "Physical Education" },
  { query: "movement curriculum", expected: "Physical Education" },
  { query: "workout mentoring", expected: "Physical Education" },
  { query: "team conditioning", expected: "Physical Education" },
  { query: "training schedules", expected: "Physical Education" },
  { query: "team coaching course", expected: "Physical Education" },
  { query: "body mechanics course", expected: "Physical Education" },
  { query: "workout curriculum", expected: "Physical Education" },
  { query: "health syllabus", expected: "Physical Education" },
  { query: "game techniques course", expected: "Physical Education" },
  { query: "body fitness studies", expected: "Physical Education" },
  { query: "movement essentials", expected: "Physical Education" },
  { query: "team wellness", expected: "Physical Education" },

  // Arts and Humanities (36 queries)
  { query: "Italian painters 1500s", expected: "Arts and Humanities" },
  { query: "blues origins", expected: "Arts and Humanities" },
  { query: "verse interpretation", expected: "Arts and Humanities" },
  { query: "marble carving methods", expected: "Arts and Humanities" },
  { query: "stage acting", expected: "Arts and Humanities" },
  { query: "cultural explorations", expected: "Arts and Humanities" },
  { query: "orchestral compositions", expected: "Arts and Humanities" },
  { query: "expressionist paintings", expected: "Arts and Humanities" },
  { query: "narrative critique", expected: "Arts and Humanities" },
  { query: "aesthetic evaluation", expected: "Arts and Humanities" },
  { query: "stage chronicles", expected: "Arts and Humanities" },
  { query: "melody crafting", expected: "Arts and Humanities" },
  { query: "timeless stories", expected: "Arts and Humanities" },
  { query: "canvas methods", expected: "Arts and Humanities" },
  { query: "creative syllabus", expected: "Arts and Humanities" },
  { query: "cultural critique", expected: "Arts and Humanities" },
  { query: "Elizabethan dramas", expected: "Arts and Humanities" },
  { query: "artistic eras", expected: "Arts and Humanities" },
  { query: "melody studies", expected: "Arts and Humanities" },
  { query: "story explorations", expected: "Arts and Humanities" },
  { query: "theatre performances", expected: "Arts and Humanities" }, // Alternative spelling
  { query: "marble carving course", expected: "Arts and Humanities" },
  { query: "orchestral course", expected: "Arts and Humanities" },
  { query: "aesthetic course", expected: "Arts and Humanities" },
  { query: "verse course", expected: "Arts and Humanities" },
  { query: "melody crafting course", expected: "Arts and Humanities" },
  { query: "Elizabethan analysis", expected: "Arts and Humanities" },
  { query: "creative essentials", expected: "Arts and Humanities" },
  { query: "stage syllabus", expected: "Arts and Humanities" },
  { query: "marble essentials", expected: "Arts and Humanities" },
  { query: "verse critique course", expected: "Arts and Humanities" },
  { query: "blues curriculum", expected: "Arts and Humanities" },
  { query: "creative explorations", expected: "Arts and Humanities" },
  { query: "cultural studies", expected: "Arts and Humanities" },
  { query: "artistic chronicles", expected: "Arts and Humanities" },
  { query: "timeless tales course", expected: "Arts and Humanities" },

  // Business and Communication (36 queries)
  { query: "promotional tactics", expected: "Business and Communication" },
  { query: "company budgeting", expected: "Business and Communication" },
  { query: "executive guidance", expected: "Business and Communication" },
  { query: "market principles", expected: "Business and Communication" },
  { query: "oratorical skills", expected: "Business and Communication" },
  { query: "enterprise functions", expected: "Business and Communication" },
  { query: "ad initiatives", expected: "Business and Communication" },
  { query: "fiscal evaluations", expected: "Business and Communication" },
  { query: "team coordination", expected: "Business and Communication" },
  { query: "company messaging", expected: "Business and Communication" },
  { query: "trade dynamics", expected: "Business and Communication" },
  { query: "press interactions", expected: "Business and Communication" },
  { query: "corporate strategies", expected: "Business and Communication" },
  { query: "consumer research", expected: "Business and Communication" },
  { query: "fiscal planning", expected: "Business and Communication" },
  { query: "enterprise correspondence", expected: "Business and Communication" },
  { query: "trade policies", expected: "Business and Communication" },
  { query: "corporate guidance", expected: "Business and Communication" },
  { query: "enterprise essentials", expected: "Business and Communication" },
  { query: "promotional essentials", expected: "Business and Communication" },
  { query: "managment techniques", expected: "Business and Communication" }, // Misspelling
  { query: "market studies", expected: "Business and Communication" },
  { query: "oratorical studies", expected: "Business and Communication" },
  { query: "enterprise syllabus", expected: "Business and Communication" },
  { query: "ad course", expected: "Business and Communication" },
  { query: "fiscal strategies", expected: "Business and Communication" },
  { query: "executive course", expected: "Business and Communication" },
  { query: "press course", expected: "Business and Communication" },
  { query: "market essentials", expected: "Business and Communication" },
  { query: "enterprise functions course", expected: "Business and Communication" },
  { query: "oratorical course", expected: "Business and Communication" },
  { query: "promotional tactics course", expected: "Business and Communication" },
  { query: "company budgeting course", expected: "Business and Communication" },
  { query: "team essentials", expected: "Business and Communication" },
  { query: "enterprise curriculum", expected: "Business and Communication" },
  { query: "market syllabus", expected: "Business and Communication" },

  // Career and Technical Education (36 queries)
  { query: "software coding camp", expected: "Career and Technical Education" },
  { query: "craft apprenticeship", expected: "Career and Technical Education" },
  { query: "tech learning", expected: "Career and Technical Education" },
  { query: "structural design", expected: "Career and Technical Education" },
  { query: "app creation", expected: "Career and Technical Education" },
  { query: "trade expertise", expected: "Career and Technical Education" },
  { query: "professional abilities", expected: "Career and Technical Education" },
  { query: "scripting essentials", expected: "Career and Technical Education" },
  { query: "mechanical prototypes", expected: "Career and Technical Education" },
  { query: "technical expertise", expected: "Career and Technical Education" },
  { query: "craft programs", expected: "Career and Technical Education" },
  { query: "digital scripting", expected: "Career and Technical Education" },
  { query: "mechanical innovations", expected: "Career and Technical Education" },
  { query: "trade credentials", expected: "Career and Technical Education" },
  { query: "job preparation", expected: "Career and Technical Education" },
  { query: "tech apprenticeship", expected: "Career and Technical Education" },
  { query: "scripting proficiency", expected: "Career and Technical Education" },
  { query: "structural systems", expected: "Career and Technical Education" },
  { query: "learn scripting", expected: "Career and Technical Education" },
  { query: "mobile app crafting", expected: "Career and Technical Education" },
  { query: "programing essentials", expected: "Career and Technical Education" }, // Misspelling
  { query: "tech syllabus", expected: "Career and Technical Education" },
  { query: "mechanical curriculum", expected: "Career and Technical Education" },
  { query: "app creation course", expected: "Career and Technical Education" },
  { query: "craft learning", expected: "Career and Technical Education" },
  { query: "scripting tutorials", expected: "Career and Technical Education" },
  { query: "craft apprenticeship course", expected: "Career and Technical Education" },
  { query: "job growth", expected: "Career and Technical Education" },
  { query: "technical abilities course", expected: "Career and Technical Education" },
  { query: "structural design course", expected: "Career and Technical Education" },
  { query: "scripting course", expected: "Career and Technical Education" },
  { query: "digital essentials", expected: "Career and Technical Education" },
  { query: "trade mastery", expected: "Career and Technical Education" },
  { query: "tech learning curriculum", expected: "Career and Technical Education" },
  { query: "tech apprenticeship syllabus", expected: "Career and Technical Education" },
  { query: "professional abilities course", expected: "Career and Technical Education" },

  // General Studies (36 queries)
  { query: "diverse learning", expected: "General Studies" },
  { query: "essential academics", expected: "General Studies" },
  { query: "study approaches", expected: "General Studies" },
  { query: "formal composition", expected: "General Studies" },
  { query: "varied disciplines", expected: "General Studies" },
  { query: "logical analysis", expected: "General Studies" },
  { query: "inquiry methods", expected: "General Studies" },
  { query: "core academics", expected: "General Studies" },
  { query: "learning methods", expected: "General Studies" },
  { query: "formal skills", expected: "General Studies" },
  { query: "mixed inquiries", expected: "General Studies" },
  { query: "scholarly prose", expected: "General Studies" },
  { query: "diverse academics", expected: "General Studies" },
  { query: "study practices", expected: "General Studies" },
  { query: "essential knowledge", expected: "General Studies" },
  { query: "formal inquiries", expected: "General Studies" },
  { query: "logical skills", expected: "General Studies" },
  { query: "essential academics course", expected: "General Studies" },
  { query: "study routines", expected: "General Studies" },
  { query: "collegiate prose", expected: "General Studies" },
  { query: "academik skills", expected: "General Studies" }, // Misspelling
  { query: "core course", expected: "General Studies" },
  { query: "diverse academics course", expected: "General Studies" },
  { query: "study approaches course", expected: "General Studies" },
  { query: "logical analysis course", expected: "General Studies" },
  { query: "inquiry methods course", expected: "General Studies" },
  { query: "varied disciplines learning", expected: "General Studies" },
  { query: "formal composition course", expected: "General Studies" },
  { query: "essential academics basics", expected: "General Studies" },
  { query: "learning methods course", expected: "General Studies" },
  { query: "diverse essentials", expected: "General Studies" },
  { query: "essential knowledge course", expected: "General Studies" },
  { query: "logical skills course", expected: "General Studies" },
  { query: "formal inquiries course", expected: "General Studies" },
  { query: "study practices course", expected: "General Studies" },
  { query: "core academics basics", expected: "General Studies" },

  // No-match queries (20 queries)
  { query: "arbitrary topic", expected: null },
  { query: "extraneous subject", expected: null },
  { query: "mixed queries", expected: null },
  { query: "broad query", expected: null },
  { query: "obscure topic", expected: null },
  { query: "ambiguous term", expected: null },
  { query: "non scholarly", expected: null },
  { query: "unrelated search", expected: null },
  { query: "off point", expected: null },
  { query: "no focus", expected: null },
  { query: "undefined topic", expected: null },
  { query: "vague question", expected: null },
  { query: "arbitrary search", expected: null },
  { query: "non academic query", expected: null },
  { query: "misc subject", expected: null },
  { query: "unclear query", expected: null },
  { query: "extraneous query", expected: null },
  { query: "broad topic", expected: null },
  { query: "off focus", expected: null },
  { query: "no classification", expected: null }
];

module.exports = testQueries;

// const testQueries = [
//   // History (36 queries)
//   { query: "Qin dynasty clay soldiers background", expected: "History" },
//   { query: "Persian Gulf conflict timeline", expected: "History" },
//   { query: "Mesopotamian societal roots", expected: "History" },
//   { query: "1815 Louisiana battle", expected: "History" },
//   { query: "Bolshevik revolt 1917", expected: "History" },
//   { query: "Song dynasty administration", expected: "History" },
//   { query: "Spanish inquisition purges", expected: "History" },
//   { query: "Korean War overview", expected: "History" },
//   { query: "Iliad war narratives", expected: "History" },
//   { query: "Japanese feudal rule", expected: "History" },
//   { query: "Platonic governance age", expected: "History" },
//   { query: "Mongol trade routes", expected: "History" },
//   { query: "Boston Tea Party causes", expected: "History" },
//   { query: "ancient military tactics", expected: "History" },
//   { query: "Mesoamerican empire fall", expected: "History" },
//   { query: "Roman Empire collapse", expected: "History" },
//   { query: "global historical patterns", expected: "History" },
//   { query: "Salem witch trials", expected: "History" },
//   { query: "Holy Roman Empire rise", expected: "History" },
//   { query: "Asian dynastic shifts", expected: "History" },
//   { query: "Crusades overview", expected: "History" },
//   { query: "Baroque building styles", expected: "History" },
//   { query: "Athenian democracy origins", expected: "History" },
//   { query: "World War I summary", expected: "History" },
//   { query: "Sengoku period Japan", expected: "History" },
//   { query: "Persian empire campaigns", expected: "History" },
//   { query: "Egyptian rulers history", expected: "History" },
//   { query: "Norman conquest 1066", expected: "History" },
//   { query: "space race 1960s", expected: "History" },
//   { query: "Zhou dynasty thought", expected: "History" },
//   { query: "historical curriculum", expected: "History" },
//   { query: "West African empire commerce", expected: "History" },
//   { query: "Cuban revolution 1959", expected: "History" },
//   { query: "human historical eras", expected: "History" },
//   { query: "Incan societal structure", expected: "History" },
//   { query: "world conflict periods", expected: "History" },

//   // Chinese Language Education (36 queries)
//   { query: "Mandarin speech nuances", expected: "Chinese Language Education" },
//   { query: "Chinese linguistic rules", expected: "Chinese Language Education" },
//   { query: "hanzi writing order", expected: "Chinese Language Education" },
//   { query: "Cantonese slang usage", expected: "Chinese Language Education" },
//   { query: "classical Chinese poems", expected: "Chinese Language Education" },
//   { query: "Mandarin tone practice", expected: "Chinese Language Education" },
//   { query: "Chinese sentence patterns", expected: "Chinese Language Education" },
//   { query: "learning Chinese characters", expected: "Chinese Language Education" },
//   { query: "pinyin pronunciation drills", expected: "Chinese Language Education" },
//   { query: "Chinese cultural stories", expected: "Chinese Language Education" },
//   { query: "Mandarin phrase practice", expected: "Chinese Language Education" },
//   { query: "Cantonese speech patterns", expected: "Chinese Language Education" },
//   { query: "Chinese script basics", expected: "Chinese Language Education" },
//   { query: "tone mastery exercises", expected: "Chinese Language Education" },
//   { query: "ancient Chinese writings", expected: "Chinese Language Education" },
//   { query: "Mandarin accent coaching", expected: "Chinese Language Education" },
//   { query: "Chinese language fluency", expected: "Chinese Language Education" },
//   { query: "Mandarin dialogue skills", expected: "Chinese Language Education" },
//   { query: "Chinese essay writing", expected: "Chinese Language Education" },
//   { query: "study Cantonese speech", expected: "Chinese Language Education" },
//   { query: "hanzi memorization tips", expected: "Chinese Language Education" },
//   { query: "Mandarin speech clarity", expected: "Chinese Language Education" },
//   { query: "Chinese idioms practice", expected: "Chinese Language Education" },
//   { query: "pinyin tone lessons", expected: "Chinese Language Education" },
//   { query: "Chinese language course", expected: "Chinese Language Education" },
//   { query: "Cantonese public speaking", expected: "Chinese Language Education" },
//   { query: "Chinese calligraphy skills", expected: "Chinese Language Education" },
//   { query: "Mandarin fluency training", expected: "Chinese Language Education" },
//   { query: "Chinese literature analysis", expected: "Chinese Language Education" },
//   { query: "online Chinese lessons", expected: "Chinese Language Education" },
//   { query: "Chinese language essentials", expected: "Chinese Language Education" },
//   { query: "hanzi recognition practice", expected: "Chinese Language Education" },
//   { query: "Chinese dialogue drills", expected: "Chinese Language Education" },
//   { query: "Mandarin syntax mastery", expected: "Chinese Language Education" },
//   { query: "Chinese speech training", expected: "Chinese Language Education" },
//   { query: "Chinese oration practice", expected: "Chinese Language Education" },

//   // English Language Education (36 queries)
//   { query: "English sentence rules", expected: "English Language Education" },
//   { query: "fluent English speaking", expected: "English Language Education" },
//   { query: "ESL learning plan", expected: "English Language Education" },
//   { query: "English word growth", expected: "English Language Education" },
//   { query: "story writing skills", expected: "English Language Education" },
//   { query: "19th-century English novels", expected: "English Language Education" },
//   { query: "English grammar basics", expected: "English Language Education" },
//   { query: "English pronunciation tips", expected: "English Language Education" },
//   { query: "argumentative essay skills", expected: "English Language Education" },
//   { query: "English speaking fluency", expected: "English Language Education" },
//   { query: "English vocabulary building", expected: "English Language Education" },
//   { query: "English reading skills", expected: "English Language Education" },
//   { query: "ESL teaching tools", expected: "English Language Education" },
//   { query: "English narrative writing", expected: "English Language Education" },
//   { query: "grammar practice drills", expected: "English Language Education" },
//   { query: "English language classes", expected: "English Language Education" },
//   { query: "English text comprehension", expected: "English Language Education" },
//   { query: "English slang expressions", expected: "English Language Education" },
//   { query: "English fluency training", expected: "English Language Education" },
//   { query: "ESL coaching support", expected: "English Language Education" },
//   { query: "English conversation practice", expected: "English Language Education" },
//   { query: "English grammar exercises", expected: "English Language Education" },
//   { query: "English reading fluency", expected: "English Language Education" },
//   { query: "ESL learner support", expected: "English Language Education" },
//   { query: "English essay composition", expected: "English Language Education" },
//   { query: "English word exercises", expected: "English Language Education" },
//   { query: "English language basics", expected: "English Language Education" },
//   { query: "English public speaking", expected: "English Language Education" },
//   { query: "English novel analysis", expected: "English Language Education" },
//   { query: "online English courses", expected: "English Language Education" },
//   { query: "English grammar lessons", expected: "English Language Education" },
//   { query: "ESL conversation skills", expected: "English Language Education" },
//   { query: "English writing techniques", expected: "English Language Education" },
//   { query: "English literature studies", expected: "English Language Education" },
//   { query: "English language program", expected: "English Language Education" },
//   { query: "English vocabulary drills", expected: "English Language Education" },

//   // Mathematics Education (36 queries)
//   { query: "tackling math problems", expected: "Mathematics Education" },
//   { query: "calculus fundamentals", expected: "Mathematics Education" },
//   { query: "geometric principles", expected: "Mathematics Education" },
//   { query: "trig ratio lessons", expected: "Mathematics Education" },
//   { query: "stats and probability", expected: "Mathematics Education" },
//   { query: "graphing linear equations", expected: "Mathematics Education" },
//   { query: "math rule applications", expected: "Mathematics Education" },
//   { query: "solving quadratic equations", expected: "Mathematics Education" },
//   { query: "geometry theorems", expected: "Mathematics Education" },
//   { query: "probability calculations", expected: "Mathematics Education" },
//   { query: "math tutoring sessions", expected: "Mathematics Education" },
//   { query: "trigonometric identities", expected: "Mathematics Education" },
//   { query: "vector math basics", expected: "Mathematics Education" },
//   { query: "integration techniques", expected: "Mathematics Education" },
//   { query: "math brain teasers", expected: "Mathematics Education" },
//   { query: "statistical data analysis", expected: "Mathematics Education" },
//   { query: "geometric shape studies", expected: "Mathematics Education" },
//   { query: "math learning program", expected: "Mathematics Education" },
//   { query: "math basics course", expected: "Mathematics Education" },
//   { query: "algebra tutoring", expected: "Mathematics Education" },
//   { query: "calculus coaching", expected: "Mathematics Education" },
//   { query: "geometry fundamentals", expected: "Mathematics Education" },
//   { query: "basic stats lessons", expected: "Mathematics Education" },
//   { query: "math essentials", expected: "Mathematics Education" },
//   { query: "trig tutoring", expected: "Mathematics Education" },
//   { query: "probability exercises", expected: "Mathematics Education" },
//   { query: "online math classes", expected: "Mathematics Education" },
//   { query: "quadratic equation drills", expected: "Mathematics Education" },
//   { query: "calculus practice", expected: "Mathematics Education" },
//   { query: "geometry studies", expected: "Mathematics Education" },
//   { query: "math proficiency course", expected: "Mathematics Education" },
//   { query: "stats tutoring", expected: "Mathematics Education" },
//   { query: "vector math course", expected: "Mathematics Education" },
//   { query: "math problem sets", expected: "Mathematics Education" },
//   { query: "trig essentials", expected: "Mathematics Education" },
//   { query: "math curriculum", expected: "Mathematics Education" },

//   // Science Education (36 queries)
//   { query: "cell division stages", expected: "Science Education" },
//   { query: "relativity principles", expected: "Science Education" },
//   { query: "organic chemistry basics", expected: "Science Education" },
//   { query: "ecological interactions", expected: "Science Education" },
//   { query: "Newton’s motion laws", expected: "Science Education" },
//   { query: "star life cycles", expected: "Science Education" },
//   { query: "geological rock layers", expected: "Science Education" },
//   { query: "DNA structure studies", expected: "Science Education" },
//   { query: "thermodynamic principles", expected: "Science Education" },
//   { query: "lab experiment skills", expected: "Science Education" },
//   { query: "atomic structure models", expected: "Science Education" },
//   { query: "evolution theories", expected: "Science Education" },
//   { query: "electromagnetic fields", expected: "Science Education" },
//   { query: "orbital mechanics", expected: "Science Education" },
//   { query: "climate patterns", expected: "Science Education" },
//   { query: "science curriculum", expected: "Science Education" },
//   { query: "chemical bonding", expected: "Science Education" },
//   { query: "optics and light", expected: "Science Education" },
//   { query: "cell biology basics", expected: "Science Education" },
//   { query: "physics experiments", expected: "Science Education" },
//   { query: "chemistry fundamentals", expected: "Science Education" },
//   { query: "astronomy basics", expected: "Science Education" },
//   { query: "genetics studies", expected: "Science Education" },
//   { query: "geology lessons", expected: "Science Education" },
//   { query: "science essentials", expected: "Science Education" },
//   { query: "physics tutoring", expected: "Science Education" },
//   { query: "biology curriculum", expected: "Science Education" },
//   { query: "molecular biology", expected: "Science Education" },
//   { query: "science learning", expected: "Science Education" },
//   { query: "ecology studies", expected: "Science Education" },
//   { query: "astronomy curriculum", expected: "Science Education" },
//   { query: "physics principles", expected: "Science Education" },
//   { query: "biology experiments", expected: "Science Education" },
//   { query: "chemistry tutoring", expected: "Science Education" },
//   { query: "scientific method", expected: "Science Education" },
//   { query: "genetics experiments", expected: "Science Education" },

//   // Social and Humanistic Education (36 queries)
//   { query: "social structures", expected: "Social and Humanistic Education" },
//   { query: "cognitive processes", expected: "Social and Humanistic Education" },
//   { query: "moral philosophy", expected: "Social and Humanistic Education" },
//   { query: "cultural anthropology", expected: "Social and Humanistic Education" },
//   { query: "civic education", expected: "Social and Humanistic Education" },
//   { query: "cultural studies basics", expected: "Social and Humanistic Education" },
//   { query: "behavioral psychology", expected: "Social and Humanistic Education" },
//   { query: "social science research", expected: "Social and Humanistic Education" },
//   { query: "philosophical reasoning", expected: "Social and Humanistic Education" },
//   { query: "ethnographic studies", expected: "Social and Humanistic Education" },
//   { query: "humanities basics", expected: "Social and Humanistic Education" },
//   { query: "cultural learning", expected: "Social and Humanistic Education" },
//   { query: "psychology theories", expected: "Social and Humanistic Education" },
//   { query: "social inequalities", expected: "Social and Humanistic Education" },
//   { query: "philosophical ideas", expected: "Social and Humanistic Education" },
//   { query: "cultural research", expected: "Social and Humanistic Education" },
//   { query: "sociological theories", expected: "Social and Humanistic Education" },
//   { query: "humanities studies", expected: "Social and Humanistic Education" },
//   { query: "psychology basics", expected: "Social and Humanistic Education" },
//   { query: "sociology fundamentals", expected: "Social and Humanistic Education" },
//   { query: "ethics education", expected: "Social and Humanistic Education" },
//   { query: "anthropology basics", expected: "Social and Humanistic Education" },
//   { query: "humanities curriculum", expected: "Social and Humanistic Education" },
//   { query: "cultural foundations", expected: "Social and Humanistic Education" },
//   { query: "psychology research", expected: "Social and Humanistic Education" },
//   { query: "sociology curriculum", expected: "Social and Humanistic Education" },
//   { query: "ethics curriculum", expected: "Social and Humanistic Education" },
//   { query: "anthropology research", expected: "Social and Humanistic Education" },
//   { query: "civic learning", expected: "Social and Humanistic Education" },
//   { query: "behavioral studies", expected: "Social and Humanistic Education" },
//   { query: "sociology basics", expected: "Social and Humanistic Education" },
//   { query: "philosophy curriculum", expected: "Social and Humanistic Education" },
//   { query: "cultural studies course", expected: "Social and Humanistic Education" },
//   { query: "cultural anthropology course", expected: "Social and Humanistic Education" },
//   { query: "humanities essentials", expected: "Social and Humanistic Education" },
//   { query: "psychology curriculum", expected: "Social and Humanistic Education" },

//   // Physical Education (36 queries)
//   { query: "fitness training", expected: "Physical Education" },
//   { query: "sports coaching", expected: "Physical Education" },
//   { query: "exercise routines", expected: "Physical Education" },
//   { query: "athletic conditioning", expected: "Physical Education" },
//   { query: "physical wellness", expected: "Physical Education" },
//   { query: "sports curriculum", expected: "Physical Education" },
//   { query: "gym workouts", expected: "Physical Education" },
//   { query: "body movement science", expected: "Physical Education" },
//   { query: "muscle training", expected: "Physical Education" },
//   { query: "athletic skills", expected: "Physical Education" },
//   { query: "health fitness plans", expected: "Physical Education" },
//   { query: "sports techniques", expected: "Physical Education" },
//   { query: "physical training", expected: "Physical Education" },
//   { query: "exercise coaching", expected: "Physical Education" },
//   { query: "team sports management", expected: "Physical Education" },
//   { query: "movement education", expected: "Physical Education" },
//   { query: "athletic programs", expected: "Physical Education" },
//   { query: "body fitness", expected: "Physical Education" },
//   { query: "workout plans", expected: "Physical Education" },
//   { query: "sports training", expected: "Physical Education" },
//   { query: "exercise basics", expected: "Physical Education" },
//   { query: "athletic essentials", expected: "Physical Education" },
//   { query: "fitness routines", expected: "Physical Education" },
//   { query: "sports education", expected: "Physical Education" },
//   { query: "physical curriculum", expected: "Physical Education" },
//   { query: "gym coaching", expected: "Physical Education" },
//   { query: "team sports training", expected: "Physical Education" },
//   { query: "exercise schedules", expected: "Physical Education" },
//   { query: "sports coaching course", expected: "Physical Education" },
//   { query: "body movement course", expected: "Physical Education" },
//   { query: "fitness curriculum", expected: "Physical Education" },
//   { query: "health fitness course", expected: "Physical Education" },
//   { query: "sports techniques course", expected: "Physical Education" },
//   { query: "physical fitness studies", expected: "Physical Education" },
//   { query: "movement basics", expected: "Physical Education" },
//   { query: "team fitness", expected: "Physical Education" },

//   // Arts and Humanities (36 queries)
//   { query: "Renaissance art masters", expected: "Arts and Humanities" },
//   { query: "jazz music history", expected: "Arts and Humanities" },
//   { query: "poetry analysis", expected: "Arts and Humanities" },
//   { query: "stone sculpting techniques", expected: "Arts and Humanities" },
//   { query: "theater performance", expected: "Arts and Humanities" },
//   { query: "cultural arts studies", expected: "Arts and Humanities" },
//   { query: "symphony compositions", expected: "Arts and Humanities" },
//   { query: "modernist art movements", expected: "Arts and Humanities" },
//   { query: "literary analysis", expected: "Arts and Humanities" },
//   { query: "art appreciation", expected: "Arts and Humanities" },
//   { query: "theater history", expected: "Arts and Humanities" },
//   { query: "music composition", expected: "Arts and Humanities" },
//   { query: "classic literature", expected: "Arts and Humanities" },
//   { query: "painting techniques", expected: "Arts and Humanities" },
//   { query: "arts curriculum", expected: "Arts and Humanities" },
//   { query: "literary critique", expected: "Arts and Humanities" },
//   { query: "Shakespearean plays", expected: "Arts and Humanities" },
//   { query: "art history studies", expected: "Arts and Humanities" },
//   { query: "music theory basics", expected: "Arts and Humanities" },
//   { query: "literature studies", expected: "Arts and Humanities" },
//   { query: "stage acting course", expected: "Arts and Humanities" },
//   { query: "sculpture course", expected: "Arts and Humanities" },
//   { query: "symphony course", expected: "Arts and Humanities" },
//   { query: "art appreciation course", expected: "Arts and Humanities" },
//   { query: "poetry course", expected: "Arts and Humanities" },
//   { query: "music composition course", expected: "Arts and Humanities" },
//   { query: "Shakespeare analysis", expected: "Arts and Humanities" },
//   { query: "arts essentials", expected: "Arts and Humanities" },
//   { query: "theater curriculum", expected: "Arts and Humanities" },
//   { query: "sculpture basics", expected: "Arts and Humanities" },
//   { query: "literary critique course", expected: "Arts and Humanities" },
//   { query: "jazz curriculum", expected: "Arts and Humanities" },
//   { query: "arts studies", expected: "Arts and Humanities" },
//   { query: "cultural arts course", expected: "Arts and Humanities" },
//   { query: "art history course", expected: "Arts and Humanities" },
//   { query: "classic literature course", expected: "Arts and Humanities" },

//   // Business and Communication (36 queries)
//   { query: "marketing strategies", expected: "Business and Communication" },
//   { query: "financial planning", expected: "Business and Communication" },
//   { query: "leadership skills", expected: "Business and Communication" },
//   { query: "economic principles", expected: "Business and Communication" },
//   { query: "public speaking", expected: "Business and Communication" },
//   { query: "business operations", expected: "Business and Communication" },
//   { query: "advertising campaigns", expected: "Business and Communication" },
//   { query: "budget analysis", expected: "Business and Communication" },
//   { query: "team leadership", expected: "Business and Communication" },
//   { query: "corporate communication", expected: "Business and Communication" },
//   { query: "market economics", expected: "Business and Communication" },
//   { query: "media relations", expected: "Business and Communication" },
//   { query: "business planning", expected: "Business and Communication" },
//   { query: "consumer behavior", expected: "Business and Communication" },
//   { query: "financial strategies", expected: "Business and Communication" },
//   { query: "business writing", expected: "Business and Communication" },
//   { query: "economic policies", expected: "Business and Communication" },
//   { query: "management skills", expected: "Business and Communication" },
//   { query: "business essentials", expected: "Business and Communication" },
//   { query: "marketing basics", expected: "Business and Communication" },
//   { query: "management fundamentals", expected: "Business and Communication" },
//   { query: "market research", expected: "Business and Communication" },
//   { query: "public speaking course", expected: "Business and Communication" },
//   { query: "business curriculum", expected: "Business and Communication" },
//   { query: "advertising course", expected: "Business and Communication" },
//   { query: "financial planning course", expected: "Business and Communication" },
//   { query: "leadership course", expected: "Business and Communication" },
//   { query: "media relations course", expected: "Business and Communication" },
//   { query: "economic basics", expected: "Business and Communication" },
//   { query: "business operations course", expected: "Business and Communication" },
//   { query: "public speaking basics", expected: "Business and Communication" },
//   { query: "marketing strategies course", expected: "Business and Communication" },
//   { query: "financial analysis course", expected: "Business and Communication" },
//   { query: "team leadership course", expected: "Business and Communication" },
//   { query: "business communication course", expected: "Business and Communication" },
//   { query: "market research course", expected: "Business and Communication" },

//   // Career and Technical Education (36 queries)
//   { query: "programming bootcamp", expected: "Career and Technical Education" },
//   { query: "trade skill training", expected: "Career and Technical Education" },
//   { query: "technology education", expected: "Career and Technical Education" },
//   { query: "engineering design", expected: "Career and Technical Education" },
//   { query: "software development", expected: "Career and Technical Education" },
//   { query: "vocational skills", expected: "Career and Technical Education" },
//   { query: "career training", expected: "Career and Technical Education" },
//   { query: "coding fundamentals", expected: "Career and Technical Education" },
//   { query: "engineering prototypes", expected: "Career and Technical Education" },
//   { query: "technical skills", expected: "Career and Technical Education" },
//   { query: "trade programs", expected: "Career and Technical Education" },
//   { query: "programming basics", expected: "Career and Technical Education" },
//   { query: "engineering innovations", expected: "Career and Technical Education" },
//   { query: "vocational certification", expected: "Career and Technical Education" },
//   { query: "job skill training", expected: "Career and Technical Education" },
//   { query: "tech training", expected: "Career and Technical Education" },
//   { query: "coding proficiency", expected: "Career and Technical Education" },
//   { query: "engineering systems", expected: "Career and Technical Education" },
//   { query: "learn programming", expected: "Career and Technical Education" },
//   { query: "app development", expected: "Career and Technical Education" },
//   { query: "coding basics", expected: "Career and Technical Education" },
//   { query: "tech curriculum", expected: "Career and Technical Education" },
//   { query: "engineering curriculum", expected: "Career and Technical Education" },
//   { query: "software development course", expected: "Career and Technical Education" },
//   { query: "trade skill learning", expected: "Career and Technical Education" },
//   { query: "programming tutorials", expected: "Career and Technical Education" },
//   { query: "trade training course", expected: "Career and Technical Education" },
//   { query: "career development", expected: "Career and Technical Education" },
//   { query: "technical skills course", expected: "Career and Technical Education" },
//   { query: "engineering design course", expected: "Career and Technical Education" },
//   { query: "coding course", expected: "Career and Technical Education" },
//   { query: "tech essentials", expected: "Career and Technical Education" },
//   { query: "vocational mastery", expected: "Career and Technical Education" },
//   { query: "tech education curriculum", expected: "Career and Technical Education" },
//   { query: "tech training syllabus", expected: "Career and Technical Education" },
//   { query: "career skills course", expected: "Career and Technical Education" },

//   // General Studies (36 queries)
//   { query: "broad education", expected: "General Studies" },
//   { query: "core academic skills", expected: "General Studies" },
//   { query: "learning strategies", expected: "General Studies" },
//   { query: "academic writing", expected: "General Studies" },
//   { query: "interdisciplinary learning", expected: "General Studies" },
//   { query: "critical thinking", expected: "General Studies" },
//   { query: "research methods", expected: "General Studies" },
//   { query: "basic academics", expected: "General Studies" },
//   { query: "study techniques", expected: "General Studies" },
//   { query: "scholarly skills", expected: "General Studies" },
//   { query: "mixed academic studies", expected: "General Studies" },
//   { query: "academic essay writing", expected: "General Studies" },
//   { query: "broad academics", expected: "General Studies" },
//   { query: "learning practices", expected: "General Studies" },
//   { query: "general knowledge", expected: "General Studies" },
//   { query: "academic research", expected: "General Studies" },
//   { query: "analytical skills", expected: "General Studies" },
//   { query: "core academics course", expected: "General Studies" },
//   { query: "study habits", expected: "General Studies" },
//   { query: "college writing", expected: "General Studies" },
//   { query: "academic fundamentals", expected: "General Studies" },
//   { query: "general curriculum", expected: "General Studies" },
//   { query: "broad academics course", expected: "General Studies" },
//   { query: "learning strategies course", expected: "General Studies" },
//   { query: "critical thinking course", expected: "General Studies" },
//   { query: "research methods course", expected: "General Studies" },
//   { query: "interdisciplinary studies", expected: "General Studies" },
//   { query: "academic writing course", expected: "General Studies" },
//   { query: "core academic basics", expected: "General Studies" },
//   { query: "study techniques course", expected: "General Studies" },
//   { query: "general essentials", expected: "General Studies" },
//   { query: "general knowledge course", expected: "General Studies" },
//   { query: "analytical skills course", expected: "General Studies" },
//   { query: "academic research course", expected: "General Studies" },
//   { query: "learning practices course", expected: "General Studies" },
//   { query: "basic academics course", expected: "General Studies" },

//   // Computer Science Education (36 queries)
//   { query: "learn Python coding", expected: "Computer Science Education" },
//   { query: "algorithm fundamentals", expected: "Computer Science Education" },
//   { query: "data structure basics", expected: "Computer Science Education" },
//   { query: "software engineering", expected: "Computer Science Education" },
//   { query: "AI programming", expected: "Computer Science Education" },
//   { query: "web development skills", expected: "Computer Science Education" },
//   { query: "database management", expected: "Computer Science Education" },
//   { query: "cybersecurity basics", expected: "Computer Science Education" },
//   { query: "network programming", expected: "Computer Science Education" },
//   { query: "machine learning intro", expected: "Computer Science Education" },
//   { query: "Java coding practice", expected: "Computer Science Education" },
//   { query: "coding tutorials", expected: "Computer Science Education" },
//   { query: "computer science course", expected: "Computer Science Education" },
//   { query: "algorithm design", expected: "Computer Science Education" },
//   { query: "data science basics", expected: "Computer Science Education" },
//   { query: "software coding", expected: "Computer Science Education" },
//   { query: "programming fundamentals", expected: "Computer Science Education" },
//   { query: "tech coding skills", expected: "Computer Science Education" },
//   { query: "AI development", expected: "Computer Science Education" },
//   { query: "web programming", expected: "Computer Science Education" },
//   { query: "database systems", expected: "Computer Science Education" },
//   { query: "cybersecurity course", expected: "Computer Science Education" },
//   { query: "networking basics", expected: "Computer Science Education" },
//   { query: "machine learning course", expected: "Computer Science Education" },
//   { query: "Python programming course", expected: "Computer Science Education" },
//   { query: "coding bootcamp", expected: "Computer Science Education" },
//   { query: "algorithm course", expected: "Computer Science Education" },
//   { query: "data structures course", expected: "Computer Science Education" },
//   { query: "software engineering course", expected: "Computer Science Education" },
//   { query: "web development course", expected: "Computer Science Education" },
//   { query: "database management course", expected: "Computer Science Education" },
//   { query: "AI programming course", expected: "Computer Science Education" },
//   { query: "cybersecurity fundamentals", expected: "Computer Science Education" },
//   { query: "network programming course", expected: "Computer Science Education" },
//   { query: "data science course", expected: "Computer Science Education" },
//   { query: "computer science basics", expected: "Computer Science Education" },

//   // Environmental Education (36 queries)
//   { query: "climate change basics", expected: "Environmental Education" },
//   { query: "ecology fundamentals", expected: "Environmental Education" },
//   { query: "sustainability studies", expected: "Environmental Education" },
//   { query: "conservation practices", expected: "Environmental Education" },
//   { query: "renewable energy sources", expected: "Environmental Education" },
//   { query: "biodiversity protection", expected: "Environmental Education" },
//   { query: "environmental policies", expected: "Environmental Education" },
//   { query: "global warming impacts", expected: "Environmental Education" },
//   { query: "wildlife preservation", expected: "Environmental Education" },
//   { query: "eco-friendly practices", expected: "Environmental Education" },
//   { query: "pollution control", expected: "Environmental Education" },
//   { query: "ecosystem management", expected: "Environmental Education" },
//   { query: "green energy solutions", expected: "Environmental Education" },
//   { query: "climate science basics", expected: "Environmental Education" },
//   { query: "sustainable living", expected: "Environmental Education" },
//   { query: "environmental studies", expected: "Environmental Education" },
//   { query: "conservation course", expected: "Environmental Education" },
//   { query: "renewable energy course", expected: "Environmental Education" },
//   { query: "biodiversity course", expected: "Environmental Education" },
//   { query: "environmental policy course", expected: "Environmental Education" },
//   { query: "global warming course", expected: "Environmental Education" },
//   { query: "wildlife conservation course", expected: "Environmental Education" },
//   { query: "ecology course", expected: "Environmental Education" },
//   { query: "sustainability course", expected: "Environmental Education" },
//   { query: "pollution control course", expected: "Environmental Education" },
//   { query: "ecosystem studies", expected: "Environmental Education" },
//   { query: "green energy course", expected: "Environmental Education" },
//   { query: "climate science course", expected: "Environmental Education" },
//   { query: "sustainable living course", expected: "Environmental Education" },
//   { query: "environmental basics", expected: "Environmental Education" },
//   { query: "conservation fundamentals", expected: "Environmental Education" },
//   { query: "biodiversity basics", expected: "Environmental Education" },
//   { query: "environmental policy basics", expected: "Environmental Education" },
//   { query: "global warming basics", expected: "Environmental Education" },
//   { query: "wildlife preservation basics", expected: "Environmental Education" },
//   { query: "ecology basics", expected: "Environmental Education" },

//   // Health Education (36 queries)
//   { query: "nutrition basics", expected: "Health Education" },
//   { query: "mental wellness practices", expected: "Health Education" },
//   { query: "public health principles", expected: "Health Education" },
//   { query: "healthy lifestyle tips", expected: "Health Education" },
//   { query: "disease prevention", expected: "Health Education" },
//   { query: "wellness education", expected: "Health Education" },
//   { query: "healthcare basics", expected: "Health Education" },
//   { query: "hygiene practices", expected: "Health Education" },
//   { query: "epidemiology studies", expected: "Health Education" },
//   { query: "stress management", expected: "Health Education" },
//   { query: "diet and nutrition", expected: "Health Education" },
//   { query: "mental health awareness", expected: "Health Education" },
//   { query: "public health campaigns", expected: "Health Education" },
//   { query: "health promotion", expected: "Health Education" },
//   { query: "preventive medicine", expected: "Health Education" },
//   { query: "wellbeing basics", expected: "Health Education" },
//   { query: "nutrition course", expected: "Health Education" },
//   { query: "mental wellness course", expected: "Health Education" },
//   { query: "public health course", expected: "Health Education" },
//   { query: "healthy lifestyle course", expected: "Health Education" },
//   { query: "disease prevention course", expected: "Health Education" },
//   { query: "wellness curriculum", expected: "Health Education" },
//   { query: "healthcare course", expected: "Health Education" },
//   { query: "hygiene course", expected: "Health Education" },
//   { query: "epidemiology course", expected: "Health Education" },
//   { query: "stress management course", expected: "Health Education" },
//   { query: "nutrition studies", expected: "Health Education" },
//   { query: "mental health course", expected: "Health Education" },
//   { query: "public health basics", expected: "Health Education" },
//   { query: "health promotion course", expected: "Health Education" },
//   { query: "preventive medicine course", expected: "Health Education" },
//   { query: "wellbeing course", expected: "Health Education" },
//   { query: "diet and nutrition course", expected: "Health Education" },
//   { query: "mental wellness basics", expected: "Health Education" },
//   { query: "health education basics", expected: "Health Education" },
//   { query: "stress management basics", expected: "Health Education" },

//   // No-match queries (20 queries)
//   { query: "random subject", expected: null },
//   { query: "unrelated topic", expected: null },
//   { query: "vague search", expected: null },
//   { query: "general question", expected: null },
//   { query: "unclear subject", expected: null },
//   { query: "non-academic topic", expected: null },
//   { query: "irrelevant query", expected: null },
//   { query: "off-topic search", expected: null },
//   { query: "no specific focus", expected: null },
//   { query: "ambiguous question", expected: null },
//   { query: "miscellaneous topic", expected: null },
//   { query: "undefined subject", expected: null },
//   { query: "broad search", expected: null },
//   { query: "non-educational query", expected: null },
//   { query: "random question", expected: null },
//   { query: "unfocused topic", expected: null },
//   { query: "irrelevant subject", expected: null },
//   { query: "general inquiry", expected: null },
//   { query: "no clear category", expected: null },
//   { query: "unspecified topic", expected: null }
// ];

// module.exports = testQueries;