import React from 'react';
import { Layout, Card, Typography, Row, Col, Divider } from 'antd';

const { Content } = Layout;
const { Title, Paragraph } = Typography;

const AiConclusion = () => {
    return (
        <Layout style={{ minHeight: '100vh', backgroundColor: '#f0f2f5' }}>
            <Content style={{ margin: '20px', padding: '20px', backgroundColor: '#fff', borderRadius: '8px' }}>
                <Title level={2} style={{ textAlign: 'center', marginBottom: '20px' }}>
                    AI Conclusion Summary
                </Title>
                <Divider />
                <Row gutter={[16, 16]}>
                    <Col span={8}>
                        <Card title="Insight 1" bordered={true} hoverable>
                            <Paragraph>
                                This section highlights the first key insight generated by the AI, providing valuable
                                information.
                            </Paragraph>
                        </Card>
                    </Col>
                    <Col span={8}>
                        <Card title="Insight 2" bordered={true} hoverable>
                            <Paragraph>
                                This section provides the second key finding, offering actionable recommendations.
                            </Paragraph>
                        </Card>
                    </Col>
                    <Col span={8}>
                        <Card title="Insight 3" bordered={true} hoverable>
                            <Paragraph>
                                This section summarizes the third takeaway, aimed at driving informed decisions.
                            </Paragraph>
                        </Card>
                    </Col>
                </Row>
                <Divider />
                <Paragraph style={{ textAlign: 'center', marginTop: '20px' }}>
                    Thank you for reviewing the AI conclusions. Please explore further for more insights!
                </Paragraph>
            </Content>
        </Layout>
    );
};

export default AiConclusion;
